language: clojure
lein: lein2

addons:
    postgresql: "9.3"

before_script:
    - createdb mammutdb
    - psql mammutdb -c 'CREATE EXTENSION "uuid-ossp";'

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
